name: Sidecar

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/sidecar.yml"
      - "docker/dockerfile.sidecar"
  workflow_dispatch:
    inputs:
      mumak_version:
        required: false

jobs:
  build-images:
    continue-on-error: true

    strategy:
      matrix:
        include:
          - release_for: Linux-x86_64
            build_on: ubuntu-latest
            suffix: amd

          - release_for: Linux-arm64
            build_on: ubuntu-arm
            suffix: arm

    runs-on: ${{ matrix.build_on }}

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/dockerfile.postgres
          push: true
          tags: ghcr.io/demeter-run/doom-patrol-metrics-exporter:${{ github.sha }}-${{ matrix.suffix }}

  build-manifest:
    needs:
      - build-images
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/demeter-run/doom-patrol-metrics-exporter

      - uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: |
            ghcr.io/demeter-run/doom-patrol-metrics-exporter:${{ github.sha }}
            ghcr.io/demeter-run/doom-patrol-metrics-exporter
          sources: |
            ghcr.io/demeter-run/doom-patrol-metrics-exporter:${{ github.sha }}-amd
            ghcr.io/demeter-run/doom-patrol-metrics-exporter:${{ github.sha }}-arm
